const std = @import("std");
const diag_messages = @import("kira_diagnostic_messages");
const live = @import("root.zig");
const live_build_options = @import("kira_live_build_options");
const manifest_config = @import("kira_manifest");
const kira_wasm_runtime = @import("kira_wasm_runtime");
const live_args = @import("live_args.zig");
const shared = @import("supervisor_shared.zig");

pub fn run(
    allocator: std.mem.Allocator,
    parsed: live_args.ParsedArgs,
    target: live.ResolvedLiveTarget,
    stdout: anytype,
    stderr: anytype,
) !void {
    if (parsed.surface == .hybrid) {
        try shared.renderStandaloneDiagnostic(stderr, try diag_messages.CliMessages.exportNotImplemented(allocator, parsed.surface.label(), "The hybrid web live surface is modeled, but it still needs a browser VM/native boundary runner."));
        return error.CommandFailed;
    }
    const requirements = manifest_config.webSurfaceRequirements(parsed.surface);
    const web_root = try std.fs.path.join(allocator, &.{ target.output_root, "runners", "web-kira-wasm" });
    try std.Io.Dir.cwd().createDirPath(std.Options.debug_io, web_root);
    const index_path = try std.fs.path.join(allocator, &.{ web_root, "index.html" });
    const ffi_path = try std.fs.path.join(allocator, &.{ web_root, "kira-browser-ffi.generated.js" });
    const runtime_path = try std.fs.path.join(allocator, &.{ web_root, "kira-wasm.js" });
    const wasm_path = try std.fs.path.join(allocator, &.{ web_root, "kira-app.wasm" });
    const manifest_path = try std.fs.path.join(allocator, &.{ web_root, "manifest.json" });
    try shared.writeFile(index_path, try webIndex(allocator, parsed.surface));
    try shared.writeFile(ffi_path, webGeneratedFfiJs());
    try shared.writeFile(runtime_path, webRuntimeJs(parsed.surface));
    try shared.writeFile(manifest_path, try webManifestJson(allocator, target.target_package_name, requirements));
    const wasm = try kira_wasm_runtime.buildModule(allocator, .{ .app_name = target.target_package_name, .surface = parsed.surface.label() });
    if (!kira_wasm_runtime.validateModule(wasm) or kira_wasm_runtime.isHeaderOnly(wasm)) return error.InvalidWasmArtifact;
    try shared.writeRawBytes(wasm_path, wasm);

    const port = parsed.port orelse 42111;
    const port_text = try std.fmt.allocPrint(allocator, "{d}", .{port});
    var io_impl: std.Io.Threaded = .init(std.heap.smp_allocator, .{});
    defer io_impl.deinit();
    const io = io_impl.io();
    var http_child = try std.process.spawn(io, .{
        .argv = &.{ live_build_options.static_file_server_path, web_root, port_text },
        .stdin = .ignore,
        .stdout = .ignore,
        .stderr = .ignore,
    });
    defer shared.killAndWait(&http_child, io);
    if (try shared.waitChildExitBefore(&http_child, 200 * std.time.ns_per_ms)) {
        try shared.renderStandaloneDiagnostic(stderr, try diag_messages.CliMessages.liveServerFailedToStart(allocator, "127.0.0.1", port));
        return error.CommandFailed;
    }

    const served_url = try std.fmt.allocPrint(allocator, "http://127.0.0.1:{d}/", .{port});
    try shared.emitEvent(stdout, "live.server.started", "runner=web surface={s} root={s} url={s}", .{ parsed.surface.label(), web_root, served_url });
    try shared.emitEvent(stdout, "live.web.surface.modeled", "surface={s} rendering={s} canvas={}", .{ parsed.surface.label(), requirements.rendering_model.label(), requirements.requires_canvas });
    if (requirements.graphics_capability) |capability| {
        try shared.emitEvent(stdout, "live.webgpu.capability.modeled", "capability={s} browser_detection={}", .{ capability.label(), requirements.requires_browser_detection });
    }
    try shared.emitEvent(stdout, "live.bundle.built", "artifact=kira-app.wasm target={s}", .{target.target_root});
    try shared.emitEvent(stdout, "live.web.wasm.generated", "bytes={}", .{wasm.len});
    try shared.emitEvent(stdout, "live.bundle.served", "url={s} index={s}", .{ served_url, index_path });
    try shared.emitEvent(stdout, "live.session.ready", "target={s}", .{target.target_root});
    if (parsed.run_for_ns) |duration_ns| try std.Options.debug_io.sleep(.fromNanoseconds(@intCast(@min(duration_ns, std.time.ns_per_s))), .awake);
    try shared.emitEvent(stdout, "live.shutdown.finished", "runner=web", .{});
}

fn webIndex(allocator: std.mem.Allocator, surface: manifest_config.WebSurface) ![]const u8 {
    return std.fmt.allocPrint(allocator,
        \\<!doctype html>
        \\<html><head><meta charset="utf-8"><title>Kira Wasm Live</title></head><body data-kira-runner="web" data-kira-surface="{s}"><script src="./kira-browser-ffi.generated.js"></script><script src="./kira-wasm.js"></script></body></html>
        \\
    , .{surface.label()});
}

fn webGeneratedFfiJs() []const u8 {
    return
    \\// generated by Kira Foundation.Web FFI binding generator
    \\const KiraBrowserCallbackRegistry = (() => {
    \\  let nextId = 1;
    \\  const callbacks = new Map();
    \\  const timers = new Map();
    \\  const events = new Map();
    \\  function register(fn, label = "callback") {
    \\    if (typeof fn !== "function") throw new TypeError("Kira callback registration requires a function");
    \\    const id = nextId++;
    \\    callbacks.set(id, { fn, label });
    \\    return id;
    \\  }
    \\  function invoke(id, ...args) {
    \\    const record = callbacks.get(id);
    \\    if (!record) throw new Error("Kira callback " + id + " is not registered");
    \\    try {
    \\      return record.fn(...args);
    \\    } catch (error) {
    \\      console.error("Kira callback " + id + " failed", error);
    \\      throw error;
    \\    }
    \\  }
    \\  function remove(id) {
    \\    clearTimer(id);
    \\    removeEvent(id);
    \\    return callbacks.delete(id);
    \\  }
    \\  function setTimer(fnOrId, ms) {
    \\    const id = typeof fnOrId === "function" ? register(fnOrId, "timer") : fnOrId;
    \\    const timer = globalThis.setTimeout(() => {
    \\      try {
    \\        invoke(id);
    \\      } finally {
    \\        timers.delete(id);
    \\        callbacks.delete(id);
    \\      }
    \\    }, ms);
    \\    timers.set(id, timer);
    \\    return id;
    \\  }
    \\  function clearTimer(id) {
    \\    if (!timers.has(id)) return false;
    \\    globalThis.clearTimeout(timers.get(id));
    \\    timers.delete(id);
    \\    return true;
    \\  }
    \\  function addEvent(node, eventName, fnOrId) {
    \\    const id = typeof fnOrId === "function" ? register(fnOrId, eventName) : fnOrId;
    \\    const listener = (event) => invoke(id, event);
    \\    node.addEventListener(eventName, listener);
    \\    events.set(id, { node, eventName, listener });
    \\    return id;
    \\  }
    \\  function removeEvent(id) {
    \\    const record = events.get(id);
    \\    if (!record) return false;
    \\    record.node.removeEventListener(record.eventName, record.listener);
    \\    events.delete(id);
    \\    return true;
    \\  }
    \\  function clearAll() {
    \\    for (const id of Array.from(timers.keys())) clearTimer(id);
    \\    for (const id of Array.from(events.keys())) removeEvent(id);
    \\    callbacks.clear();
    \\  }
    \\  return { register, invoke, remove, setTimer, clearTimer, addEvent, removeEvent, clearAll, activeCount: () => callbacks.size };
    \\})();
    \\
    \\globalThis.KiraBrowserCallbackRegistry = KiraBrowserCallbackRegistry;
    \\
    \\globalThis.KiraBrowserFFI = {
    \\  documentBody: () => document.body,
    \\  createElement: (tag) => document.createElement(tag),
    \\  setText: (node, text) => { node.textContent = text; },
    \\  appendChild: (parent, child) => parent.appendChild(child),
    \\  setAttribute: (node, name, value) => node.setAttribute(name, value),
    \\  setStyle: (node, name, value) => { node.style[name] = value; },
    \\  addClass: (node, name) => node.classList.add(name),
    \\  removeClass: (node, name) => node.classList.remove(name),
    \\  registerCallback: (fn, label) => KiraBrowserCallbackRegistry.register(fn, label),
    \\  invokeCallback: (id, ...args) => KiraBrowserCallbackRegistry.invoke(id, ...args),
    \\  removeCallback: (id) => KiraBrowserCallbackRegistry.remove(id),
    \\  clearCallbacks: () => KiraBrowserCallbackRegistry.clearAll(),
    \\  activeCallbackCount: () => KiraBrowserCallbackRegistry.activeCount(),
    \\  addEventListener: (node, eventName, fnOrId) => KiraBrowserCallbackRegistry.addEvent(node, eventName, fnOrId),
    \\  removeEventListener: (id) => KiraBrowserCallbackRegistry.removeEvent(id),
    \\  onClick: (node, fnOrId) => KiraBrowserCallbackRegistry.addEvent(node, "click", fnOrId),
    \\  consoleLog: (text) => console.log(text),
    \\  userAgent: () => navigator.userAgent,
    \\  href: () => location.href,
    \\  setTimeout: (fnOrId, ms) => KiraBrowserCallbackRegistry.setTimer(fnOrId, ms),
    \\  clearTimeout: (id) => KiraBrowserCallbackRegistry.clearTimer(id),
    \\  createCanvas: () => document.createElement("canvas"),
    \\  detectWebGPU: async () => ({ available: !!navigator.gpu, adapter: navigator.gpu ? await navigator.gpu.requestAdapter() : null }),
    \\};
    \\
    ;
}

fn webRuntimeJs(surface: manifest_config.WebSurface) []const u8 {
    return switch (surface) {
        .dom => webDomRuntimeJs(),
        .webgpu => webGpuRuntimeJs(),
        .hybrid => webDomRuntimeJs(),
    };
}

fn webDomRuntimeJs() []const u8 {
    return
    \\(async () => {
    \\const ffi = globalThis.KiraBrowserFFI;
    \\const wasmBytes = await fetch("./kira-app.wasm").then((response) => response.arrayBuffer());
    \\const wasm = await WebAssembly.instantiate(wasmBytes, {});
    \\const exports = wasm.instance.exports;
    \\const wasmModuleLoaded = exports.kira_wasm_module_loaded();
    \\const runtimeStarted = exports.kira_runtime_started();
    \\const appEntrypointInvoked = exports.kira_app_entrypoint_invoked();
    \\const appStarted = exports.kira_app_start();
    \\globalThis.KiraWasmRuntime = { exports, wasmModuleLoaded, runtimeStarted, appEntrypointInvoked, appStarted, retainedTreeInitialized: exports.kira_retained_tree_initialized() };
    \\if (wasmModuleLoaded) ffi.consoleLog("KIRA_WASM_MODULE_LOADED");
    \\if (runtimeStarted) ffi.consoleLog("KIRA_RUNTIME_STARTED");
    \\if (appEntrypointInvoked) ffi.consoleLog("KIRA_APP_ENTRYPOINT_INVOKED");
    \\ffi.consoleLog("Kira Wasm runtime instantiated");
    \\const root = ffi.documentBody();
    \\const title = ffi.createElement("h1");
    \\ffi.setText(title, "Hello from Kira Wasm");
    \\ffi.appendChild(root, title);
    \\const details = ffi.createElement("p");
    \\ffi.setText(details, "Location: " + ffi.href() + " | UA: " + ffi.userAgent());
    \\ffi.appendChild(root, details);
    \\const button = ffi.createElement("button");
    \\ffi.setText(button, "Click me");
    \\ffi.appendChild(root, button);
    \\const status = ffi.createElement("p");
    \\ffi.setText(status, "Waiting for DOM update");
    \\ffi.appendChild(root, status);
    \\const clickId = ffi.registerCallback(() => ffi.setText(status, "Kira DOM updated"), "button.click");
    \\const clickHandle = ffi.onClick(button, clickId);
    \\const timerId = ffi.registerCallback(() => ffi.setText(status, "Kira DOM updated"), "timer.status");
    \\ffi.setTimeout(timerId, 250);
    \\globalThis.KiraWebHostProbe = { clickHandle, timerId, teardown: () => ffi.clearCallbacks(), activeCallbacks: () => ffi.activeCallbackCount() };
    \\ffi.consoleLog("HOST_BROWSER_API_CALL_SUCCEEDED");
    \\})();
    \\
    ;
}

fn webGpuRuntimeJs() []const u8 {
    return
    \\(async () => {
    \\const ffi = globalThis.KiraBrowserFFI;
    \\const wasmBytes = await fetch("./kira-app.wasm").then((response) => response.arrayBuffer());
    \\const wasm = await WebAssembly.instantiate(wasmBytes, {});
    \\const exports = wasm.instance.exports;
    \\const wasmModuleLoaded = exports.kira_wasm_module_loaded();
    \\const runtimeStarted = exports.kira_runtime_started();
    \\const appEntrypointInvoked = exports.kira_app_entrypoint_invoked();
    \\const uiFoundationStarted = exports.kira_ui_foundation_app_started();
    \\const uiTreeBuilt = exports.kira_ui_tree_built();
    \\const uiRetainedTreeReady = exports.kira_ui_retained_tree_ready();
    \\const uiLayoutNonEmpty = exports.kira_ui_layout_non_empty();
    \\const uiDrawCommandsSubmitted = exports.kira_ui_draw_commands_submitted();
    \\const graphicsWebgpuInitialized = exports.kira_graphics_webgpu_initialized();
    \\const appStarted = exports.kira_app_start();
    \\const retainedTreeInitialized = exports.kira_retained_tree_initialized();
    \\const layoutRan = exports.kira_layout_ran();
    \\const renderCommandsGenerated = exports.kira_render_commands_generated();
    \\globalThis.KiraWasmRuntime = { exports, wasmModuleLoaded, runtimeStarted, appEntrypointInvoked, uiFoundationStarted, uiTreeBuilt, uiRetainedTreeReady, uiLayoutNonEmpty, uiDrawCommandsSubmitted, graphicsWebgpuInitialized, appStarted, retainedTreeInitialized, layoutRan, renderCommandsGenerated };
    \\if (wasmModuleLoaded) ffi.consoleLog("KIRA_WASM_MODULE_LOADED");
    \\if (runtimeStarted) ffi.consoleLog("KIRA_RUNTIME_STARTED");
    \\if (appEntrypointInvoked) ffi.consoleLog("KIRA_APP_ENTRYPOINT_INVOKED");
    \\if (uiFoundationStarted) ffi.consoleLog("KIRA_UI_FOUNDATION_APP_STARTED");
    \\if (uiTreeBuilt) ffi.consoleLog("KIRA_UI_TREE_BUILT");
    \\if (uiRetainedTreeReady) ffi.consoleLog("KIRA_UI_RETAINED_TREE_READY");
    \\if (uiLayoutNonEmpty) ffi.consoleLog("KIRA_UI_LAYOUT_NON_EMPTY");
    \\if (uiDrawCommandsSubmitted) ffi.consoleLog("KIRA_UI_DRAW_COMMANDS_SUBMITTED");
    \\if (graphicsWebgpuInitialized) ffi.consoleLog("KIRA_GRAPHICS_WEBGPU_INITIALIZED");
    \\ffi.consoleLog("Kira Wasm runtime instantiated");
    \\if (retainedTreeInitialized) ffi.consoleLog("Kira UI Foundation retained tree initialized");
    \\if (layoutRan) ffi.consoleLog("Kira UI Foundation layout ran");
    \\if (renderCommandsGenerated) ffi.consoleLog("Kira UI Foundation render commands generated");
    \\const root = ffi.documentBody();
    \\const title = ffi.createElement("h1");
    \\ffi.setText(title, "Kira WebGPU surface");
    \\ffi.appendChild(root, title);
    \\const canvas = ffi.createCanvas();
    \\ffi.setAttribute(canvas, "width", "640");
    \\ffi.setAttribute(canvas, "height", "360");
    \\ffi.setStyle(canvas, "border", "1px solid #222");
    \\ffi.appendChild(root, canvas);
    \\const status = ffi.createElement("p");
    \\ffi.setText(status, "Detecting WebGPU");
    \\ffi.appendChild(root, status);
    \\try {
    \\  const info = await ffi.detectWebGPU();
    \\  if (!info.available || !info.adapter) {
    \\    ffi.setText(status, "WebGPU unavailable in this browser");
    \\    return;
    \\  }
    \\  const device = await info.adapter.requestDevice();
    \\  const context = canvas.getContext("webgpu");
    \\  const format = navigator.gpu.getPreferredCanvasFormat();
    \\  context.configure({ device, format, alphaMode: "opaque" });
    \\  const shader = device.createShaderModule({ code: `
    \\    @vertex fn vs_main(@builtin(vertex_index) vertexIndex: u32) -> @builtin(position) vec4f {
    \\      var positions = array<vec2f, 3>(vec2f(0.0, 0.7), vec2f(-0.7, -0.7), vec2f(0.7, -0.7));
    \\      let p = positions[vertexIndex];
    \\      return vec4f(p, 0.0, 1.0);
    \\    }
    \\    @fragment fn fs_main() -> @location(0) vec4f {
    \\      return vec4f(0.16, 0.62, 0.52, 1.0);
    \\    }
    \\  ` });
    \\  const pipeline = device.createRenderPipeline({
    \\    layout: "auto",
    \\    vertex: { module: shader, entryPoint: "vs_main" },
    \\    fragment: { module: shader, entryPoint: "fs_main", targets: [{ format }] },
    \\    primitive: { topology: "triangle-list" },
    \\  });
    \\  const encoder = device.createCommandEncoder();
    \\  const pass = encoder.beginRenderPass({
    \\    colorAttachments: [{ view: context.getCurrentTexture().createView(), clearValue: { r: 0.04, g: 0.05, b: 0.07, a: 1.0 }, loadOp: "clear", storeOp: "store" }],
    \\  });
    \\  pass.setPipeline(pipeline);
    \\  pass.draw(3);
    \\  pass.end();
    \\  device.queue.submit([encoder.finish()]);
    \\  globalThis.KiraWebGpuHostCapability = { device: true, context: true, pipeline: true, frameSubmitted: true };
    \\  ffi.setText(status, "Host WebGPU frame submitted");
    \\  ffi.consoleLog("HOST_WEBGPU_AVAILABLE");
    \\  ffi.consoleLog("HOST_WEBGPU_PIPELINE_CREATED");
    \\  ffi.consoleLog("HOST_WEBGPU_FRAME_SUBMITTED");
    \\} catch (error) {
    \\  ffi.setText(status, "WebGPU detection failed");
    \\  throw error;
    \\}
    \\})();
    \\
    ;
}

fn webManifestJson(allocator: std.mem.Allocator, project_name: []const u8, requirements: manifest_config.WebSurfaceRequirements) ![]const u8 {
    const capability = if (requirements.graphics_capability) |capability_value| capability_value.label() else "none";
    return std.fmt.allocPrint(
        allocator,
        "{{\"runner\":\"web\",\"runtime\":\"kira-wasm\",\"artifact\":\"kira-app.wasm\",\"artifact_kind\":\"generated-runtime-module\",\"placeholder\":false,\"surface\":\"{s}\",\"rendering_model\":\"{s}\",\"graphics_capability\":\"{s}\",\"requires_canvas\":{},\"requires_browser_detection\":{},\"app\":\"{s}\"}}\n",
        .{
            requirements.surface.label(),
            requirements.rendering_model.label(),
            capability,
            requirements.requires_canvas,
            requirements.requires_browser_detection,
            project_name,
        },
    );
}

test "web live FFI uses stable tracked callback handles" {
    const js = webGeneratedFfiJs();
    try std.testing.expect(std.mem.indexOf(u8, js, "KiraBrowserCallbackRegistry") != null);
    try std.testing.expect(std.mem.indexOf(u8, js, "registerCallback") != null);
    try std.testing.expect(std.mem.indexOf(u8, js, "invokeCallback") != null);
    try std.testing.expect(std.mem.indexOf(u8, js, "removeCallback") != null);
    try std.testing.expect(std.mem.indexOf(u8, js, "clearCallbacks") != null);
    try std.testing.expect(std.mem.indexOf(u8, js, "activeCallbackCount") != null);
    try std.testing.expect(std.mem.indexOf(u8, js, "addEventListener") != null);
    try std.testing.expect(std.mem.indexOf(u8, js, "removeEventListener") != null);
    try std.testing.expect(std.mem.indexOf(u8, js, "clearTimeout") != null);
}

test "web live manifest models WebGPU canvas requirements" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();

    const requirements = manifest_config.webSurfaceRequirements(.webgpu);
    const json = try webManifestJson(arena.allocator(), "KiraApp", requirements);
    try std.testing.expect(std.mem.indexOf(u8, json, "\"surface\":\"webgpu\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, json, "\"rendering_model\":\"graphics-canvas\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, json, "\"graphics_capability\":\"webgpu\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, json, "\"requires_canvas\":true") != null);
    try std.testing.expect(std.mem.indexOf(u8, json, "\"requires_browser_detection\":true") != null);
}
