[package]
name = "Foundation"
version = "0.1.0"
kind = "library"
kira = "0.1.0"
module_root = "Foundation"
native_libraries = ["NativeLibs/FS.toml"]

[defaults]
execution_mode = "vm"
build_target = "host"
