// AppDelegate.swift — AUTO-GENERATED by kira build --target ios
// Do not edit. Re-generated on every build.

import Foundation
import KiraVM

private let kiraWindowTitle: UnsafePointer<CChar>? = ("Kira Foundation Demo" as NSString).utf8String

@_cdecl("kira_init")
func kiraInitExport() {
    KiraGeneratedBootstrap.shared.runCallback(named: "graphics_on_init")
}

@_cdecl("kira_frame")
func kiraFrameExport() {
    KiraGeneratedBootstrap.shared.runCallback(named: "graphics_on_frame")
}

@_cdecl("kira_cleanup")
func kiraCleanupExport() {
    KiraGeneratedBootstrap.shared.runCallback(named: "graphics_on_cleanup")
}

@_cdecl("kira_event")
func kiraEventExport(_ event: UnsafePointer<sapp_event>?) {
    KiraGeneratedBootstrap.shared.handleEvent(event)
}

@main
enum KiraAppLauncher {
    static func main() {
        do {
            try KiraGeneratedBootstrap.shared.prepare()
            var desc = sapp_desc()
            desc.init_cb = kiraInitExport
            desc.frame_cb = kiraFrameExport
            desc.cleanup_cb = kiraCleanupExport
            desc.event_cb = kiraEventExport
            desc.width = 960
            desc.height = 640
            desc.sample_count = 1
            desc.high_dpi = true
            desc.window_title = kiraWindowTitle
            desc.logger.func = slog_func
            sapp_run(&desc)
        } catch {
            fatalError("Failed to launch UIDemoSample: \(error)")
        }
    }
}

private final class KiraGeneratedBootstrap {
    static let shared = KiraGeneratedBootstrap()

    private let controller = KiraEmbeddedAppController()

    func prepare() throws {
        guard let bytecodeURL = Bundle.main.url(forResource: "UIDemoSample", withExtension: "kirbc") else {
            throw NSError(domain: "KiraApp", code: 1, userInfo: [NSLocalizedDescriptionKey: "Missing bundled bytecode for UIDemoSample"])
        }

        let manifestURL = Bundle.main.url(forResource: "UIDemoSample.kirpatch", withExtension: "json")
        let environment = ProcessInfo.processInfo.environment
        #if DEBUG
        let sessionID = environment["KIRA_PATCH_SESSION"]
        let sessionToken = environment["KIRA_PATCH_TOKEN"]
        let patchHost = environment["KIRA_PATCH_HOST"]
        let patchPort = environment["KIRA_PATCH_PORT"].flatMap(UInt16.init)
        let debugModeEnabled = sessionID != nil && sessionToken != nil
        #else
        let sessionID: String? = nil
        let sessionToken: String? = nil
        let patchHost: String? = nil
        let patchPort: UInt16? = nil
        let debugModeEnabled = false
        #endif

        try controller.prepare(config: .init(
            appName: "UIDemoSample",
            projectName: "UIDemoSample",
            targetAppIdentifier: "com.kira.uidemosample",
            initialBytecodeURL: bytecodeURL,
            initialManifestURL: manifestURL,
            debugModeEnabled: debugModeEnabled,
            sessionID: sessionID,
            sessionToken: sessionToken,
            patchHost: patchHost,
            patchPort: patchPort
        ))
    }

    func runCallback(named functionName: String) {
        controller.runCallback(named: functionName)
    }

    func runCallback(named functionName: String, args: [KiraValue]) {
        controller.runCallback(named: functionName, args: args)
    }

    func handleEvent(_ event: UnsafePointer<sapp_event>?) {
        guard let event else {
            return
        }
        // Foundation layout runs in window-point coordinates, not retina-scaled framebuffer pixels.
        let width = Int(event.pointee.window_width)
        let height = Int(event.pointee.window_height)
        guard width > 0 && height > 0 else {
            return
        }
        runCallback(named: "graphics_on_resize", args: [.int(Int64(width)), .int(Int64(height))])
    }
}
