[package]
name = "SokolGfxKira"
version = "0.1.0"
kira = ">=1.0.0"
license = "Apache-2.0"

[targets]
macos = true
windows = true

[dependencies]
"Kira.Fondation" = "0.1.0"

[build]
optimization = "debug"
hotReload = false
incrementalBuild = true
executionMode = "runtime"
