import Foundation

public struct BindgenEngine: Sendable {
    public init() {}

    public func generate(headerText: String, libraryName: String) -> String {
        // Minimal, deterministic bindgen for a small subset of C function prototypes:
        //   <ret> <name>(<args>);
        // Each arg: <type> <name>
        let lines = headerText.split(separator: "\n", omittingEmptySubsequences: false)
        var out: [String] = []
        out.append("// Auto-generated by kira bindgen")
        out.append("")
        out.append("@ffi(lib: \"\(libraryName)\")")

        let protoRegex = try? NSRegularExpression(pattern: #"^\s*([_A-Za-z][_A-Za-z0-9\s\*]+)\s+([_A-Za-z][_A-Za-z0-9]*)\s*\((.*)\)\s*;\s*$"#)
        for lineSub in lines {
            let line = String(lineSub)
            guard let protoRegex else { break }
            let range = NSRange(location: 0, length: (line as NSString).length)
            guard let m = protoRegex.firstMatch(in: line, range: range) else { continue }
            let ret = (line as NSString).substring(with: m.range(at: 1)).trimmingCharacters(in: .whitespaces)
            let name = (line as NSString).substring(with: m.range(at: 2)).trimmingCharacters(in: .whitespaces)
            let argsText = (line as NSString).substring(with: m.range(at: 3)).trimmingCharacters(in: .whitespaces)
            let args = argsText == "void" || argsText.isEmpty ? [] : argsText.split(separator: ",").map(String.init)

            var kiraArgs: [String] = []
            for a in args {
                let parts = a.trimmingCharacters(in: .whitespaces).split(separator: " ")
                if parts.count >= 2 {
                    let argName = String(parts.last!)
                    let argType = parts.dropLast().joined(separator: " ")
                    kiraArgs.append("\(argName): \(mapCTypeToKira(argType))")
                } else if parts.count == 1 {
                    kiraArgs.append("arg: \(mapCTypeToKira(String(parts[0])))")
                }
            }

            out.append("extern function \(name)(\(kiraArgs.joined(separator: ", "))) -> \(mapCTypeToKira(ret))")
            out.append("")
        }

        if out.last == "" { _ = out.popLast() }
        return out.joined(separator: "\n")
    }

    private func mapCTypeToKira(_ c: String) -> String {
        let t = c.replacingOccurrences(of: "const", with: "")
            .replacingOccurrences(of: "struct", with: "")
            .trimmingCharacters(in: .whitespaces)
        if t.contains("*") { return "CPointer<CVoid>" }
        switch t {
        case "int": return "CInt32"
        case "unsigned int": return "CUInt32"
        case "long": return "CInt64"
        case "unsigned long": return "CUInt64"
        case "float": return "CFloat"
        case "double": return "CDouble"
        case "void": return "CVoid"
        case "char": return "CInt8"
        case "unsigned char": return "CUInt8"
        default:
            // Preserve typedef names.
            return t.replacingOccurrences(of: " ", with: "")
        }
    }
}
