pub const OpCode = enum(u8) {
    const_int,
    const_float,
    const_string,
    const_bool,
    const_null_ptr,
    const_function,
    const_closure,
    alloc_struct,
    alloc_native_state,
    alloc_array,
    add,
    subtract,
    multiply,
    divide,
    modulo,
    compare,
    unary,
    store_local,
    load_local,
    local_ptr,
    subobject_ptr,
    field_ptr,
    recover_native_state,
    native_state_field_get,
    native_state_field_set,
    array_len,
    array_get,
    array_set,
    load_indirect,
    store_indirect,
    copy_indirect,
    branch,
    jump,
    label,
    print,
    call_runtime,
    call_native,
    call_value,
    ret,
};

pub const Instruction = union(OpCode) {
    const_int: struct { dst: u32, value: i64 },
    const_float: struct { dst: u32, value: f64 },
    const_string: struct { dst: u32, value: []const u8 },
    const_bool: struct { dst: u32, value: bool },
    const_null_ptr: struct { dst: u32 },
    const_function: struct { dst: u32, function_id: u32, representation: FunctionConstRepresentation = .callable_value },
    const_closure: struct { dst: u32, function_id: u32, captures: []const u32 },
    alloc_struct: struct { dst: u32, type_name: []const u8 },
    alloc_native_state: struct { dst: u32, src: u32, type_name: []const u8, type_id: u64 },
    alloc_array: struct { dst: u32, len: u32 },
    add: struct { dst: u32, lhs: u32, rhs: u32 },
    subtract: struct { dst: u32, lhs: u32, rhs: u32 },
    multiply: struct { dst: u32, lhs: u32, rhs: u32 },
    divide: struct { dst: u32, lhs: u32, rhs: u32 },
    modulo: struct { dst: u32, lhs: u32, rhs: u32 },
    compare: struct { dst: u32, lhs: u32, rhs: u32, op: CompareOp },
    unary: struct { dst: u32, src: u32, op: UnaryOp },
    store_local: struct { local: u32, src: u32 },
    load_local: struct { dst: u32, local: u32 },
    local_ptr: struct { dst: u32, local: u32 },
    subobject_ptr: struct { dst: u32, base: u32, offset: u32 },
    field_ptr: struct { dst: u32, base: u32, base_type_name: []const u8, field_index: u32, field_ty: TypeRef },
    recover_native_state: struct { dst: u32, state: u32, type_name: []const u8, type_id: u64 },
    native_state_field_get: struct { dst: u32, state: u32, field_index: u32, field_ty: TypeRef },
    native_state_field_set: struct { state: u32, field_index: u32, src: u32, field_ty: TypeRef },
    array_len: struct { dst: u32, array: u32 },
    array_get: struct { dst: u32, array: u32, index: u32, ty: TypeRef },
    array_set: struct { array: u32, index: u32, src: u32 },
    load_indirect: struct { dst: u32, ptr: u32, ty: TypeRef },
    store_indirect: struct { ptr: u32, src: u32, ty: TypeRef },
    copy_indirect: struct { dst_ptr: u32, src_ptr: u32, type_name: []const u8 },
    branch: struct { condition: u32, true_label: u32, false_label: u32 },
    jump: struct { label: u32 },
    label: struct { id: u32 },
    print: struct { src: u32, ty: TypeRef },
    call_runtime: struct { function_id: u32, args: []const u32, dst: ?u32 = null },
    call_native: struct { function_id: u32, args: []const u32, dst: ?u32 = null, return_ty: TypeRef = .{ .kind = .void } },
    call_value: struct { callee: u32, args: []const u32, dst: ?u32 = null },
    ret: struct { src: ?u32 = null },
};

pub const FunctionConstRepresentation = enum(u8) {
    callable_value,
    native_callback,
};

pub const CompareOp = enum(u8) {
    equal,
    not_equal,
    less,
    less_equal,
    greater,
    greater_equal,
};

pub const UnaryOp = enum(u8) {
    negate,
    not,
};

pub const TypeRef = struct {
    kind: Kind,
    name: ?[]const u8 = null,

    pub const Kind = enum(u8) {
        void,
        integer,
        float,
        string,
        boolean,
        array,
        raw_ptr,
        ffi_struct,
    };
};
