// sokol_impl.m — AUTO-GENERATED by kira build
// Do not edit.
#define SOKOL_IMPL
#define SOKOL_NO_ENTRY
#define SOKOL_METAL
#define SOKOL_METAL_MACOS

#import <Metal/Metal.h>
#import <MetalKit/MetalKit.h>
#import <QuartzCore/QuartzCore.h>

#include "vendor/sokol/sokol_app.h"
#include "vendor/sokol/sokol_gfx.h"
#include "vendor/sokol/sokol_glue.h"
#include "vendor/sokol/sokol_log.h"