// AppDelegate.swift — AUTO-GENERATED by kira build --target macos
// Do not edit. Re-generated on every build.

import Foundation
import KiraVM

private let kiraWindowTitle: UnsafePointer<CChar>? = ("Kira Foundation Demo" as NSString).utf8String

@_cdecl("kira_init")
func kiraInitExport() {
    KiraGeneratedBootstrap.shared.runCallback(named: "graphics_on_init")
}

@_cdecl("kira_frame")
func kiraFrameExport() {
    KiraGeneratedBootstrap.shared.runCallback(named: "graphics_on_frame")
}

@_cdecl("kira_cleanup")
func kiraCleanupExport() {
    KiraGeneratedBootstrap.shared.runCallback(named: "graphics_on_cleanup")
}

@_cdecl("kira_event")
func kiraEventExport(_ event: UnsafePointer<sapp_event>?) {
    KiraGeneratedBootstrap.shared.handleEvent(event)
}

@main
enum KiraAppLauncher {
    static func main() {
        do {
            try KiraGeneratedBootstrap.shared.prepare()
            var desc = sapp_desc()
            desc.init_cb = kiraInitExport
            desc.frame_cb = kiraFrameExport
            desc.cleanup_cb = kiraCleanupExport
            desc.event_cb = kiraEventExport
            desc.width = 960
            desc.height = 640
            desc.sample_count = 1
            desc.high_dpi = true
            desc.window_title = kiraWindowTitle
            desc.logger.func = slog_func
            sapp_run(&desc)
        } catch {
            fatalError("Failed to launch UIDemoSample: \(error)")
        }
    }
}

private final class KiraGeneratedBootstrap {
    static let shared = KiraGeneratedBootstrap()

    private var vm: VirtualMachine?

    func prepare() throws {
        if vm != nil {
            return
        }

        guard let bytecodeURL = Bundle.main.url(forResource: "UIDemoSample", withExtension: "kirbc") else {
            throw NSError(domain: "KiraApp", code: 1, userInfo: [NSLocalizedDescriptionKey: "Missing bundled bytecode for UIDemoSample"])
        }

        let data = try Data(contentsOf: bytecodeURL)
        let module = try BytecodeLoader().load(data: data)
        let loadedVM = VirtualMachine(module: module, output: { message in
            print(message)
        })

        if module.functions.contains(where: { $0.name == "__kira_init_globals" }) {
            _ = try loadedVM.run(function: "__kira_init_globals")
        }
        _ = try loadedVM.run(function: "main")
        vm = loadedVM
    }

    func runCallback(named functionName: String) {
        guard let vm else {
            print("[KiraRuntime] runtime not prepared for \(functionName)")
            return
        }
        do {
            _ = try vm.run(function: functionName)
        } catch {
            print("[KiraRuntime] \(functionName) failed: \(error)")
        }
    }

    func handleEvent(_ event: UnsafePointer<sapp_event>?) {
        _ = event
    }
}
