// sokol_impl.m — AUTO-GENERATED by kira build
// Do not edit.
#define SOKOL_IMPL
#define SOKOL_NO_ENTRY
#define SOKOL_METAL
#define SOKOL_METAL_MACOS
#define SOKOL_API_IMPL __attribute__((visibility("default")))
#define SOKOL_API_DECL extern __attribute__((visibility("default")))
#define SOKOL_APP_API_DECL extern __attribute__((visibility("default")))
#define SOKOL_GLUE_API_DECL extern __attribute__((visibility("default")))

#import <Metal/Metal.h>
#import <MetalKit/MetalKit.h>
#import <QuartzCore/QuartzCore.h>

#include "vendor/sokol/sokol_app.h"
#include "vendor/sokol/sokol_gfx.h"
#include "vendor/sokol/sokol_glue.h"
#include "vendor/sokol/sokol_log.h"

__attribute__((visibility("default"))) void kira_sg_setup(void) {
    sg_desc desc = {0};
    desc.environment = sglue_environment();
    desc.logger.func = slog_func;
    sg_setup(&desc);
}