// Render Kira bindings from a parsed C header.

use std::collections::BTreeSet;

use crate::ast::LinkDirective;
use crate::compiler::ffi::{CFunction, CType, ParsedHeader};

pub fn render_bindings(link: &LinkDirective, parsed: &ParsedHeader) -> String {
    let mut out = String::new();
    out.push_str("// Generated by `kira ffi`. Do not edit.\n\n");
    out.push_str("@Link(\"");
    out.push_str(&escape_kira_string(&link.library));
    out.push_str("\", header: \"");
    out.push_str(&escape_kira_string(&link.header));
    out.push_str("\")\n\n");

    let mut opaque_types = BTreeSet::<String>::new();
    for name in &parsed.opaque_typedefs {
        opaque_types.insert(name.clone());
    }

    let mut struct_defs: Vec<(String, Vec<String>)> = Vec::new();
    for structure in &parsed.structs {
        let mut fields = Vec::new();
        for field in &structure.fields {
            let ty = kira_type_name(&field.ty, &mut opaque_types);
            fields.push(format!("{}: {}", field.name, ty));
        }
        struct_defs.push((structure.name.clone(), fields));
    }

    let mut functions = Vec::new();
    for function in &parsed.functions {
        let signature = render_function(function, &mut opaque_types);
        functions.push(signature);
    }

    for name in &opaque_types {
        out.push_str("opaque ");
        out.push_str(name);
        out.push_str(";\n");
    }

    if !opaque_types.is_empty() {
        out.push('\n');
    }

    for (name, fields) in struct_defs {
        out.push_str("struct ");
        out.push_str(&name);
        out.push_str(" {\n");
        if fields.is_empty() {
            out.push_str("}\n\n");
            continue;
        }
        for field in fields {
            out.push_str("    ");
            out.push_str(&field);
            out.push_str(",\n");
        }
        out.push_str("}\n\n");
    }

    for signature in functions {
        out.push_str(&signature);
        out.push('\n');
    }

    out
}

fn render_function(function: &CFunction, opaque: &mut BTreeSet<String>) -> String {
    let mut out = String::new();
    out.push_str("extern func ");
    out.push_str(&function.name);
    out.push('(');
    let mut params = Vec::new();
    for (index, param) in function.params.iter().enumerate() {
        let name = param
            .name
            .clone()
            .unwrap_or_else(|| format!("arg{index}"));
        let ty = kira_type_name(&param.ty, opaque);
        params.push(format!("{name}: {ty}"));
    }
    out.push_str(&params.join(", "));
    out.push(')');
    if !matches!(function.return_type, CType::Void) {
        let ty = kira_type_name(&function.return_type, opaque);
        out.push_str(" -> ");
        out.push_str(&ty);
    }
    out.push_str(";");
    out
}

fn kira_type_name(ty: &CType, opaque: &mut BTreeSet<String>) -> String {
    match ty {
        CType::Void => "unit".to_string(),
        CType::Bool => "bool".to_string(),
        CType::Int64 => "int".to_string(),
        CType::Double => "float".to_string(),
        CType::Named(name) => name.clone(),
        CType::Pointer { base, .. } => {
            let name = opaque_pointer_name(base);
            opaque.insert(name.clone());
            name
        }
    }
}

fn opaque_pointer_name(base: &CType) -> String {
    match base {
        CType::Void => "void_ptr".to_string(),
        CType::Named(name) => format!("{name}Ptr"),
        CType::Bool => "bool_ptr".to_string(),
        CType::Int64 => "int64_ptr".to_string(),
        CType::Double => "double_ptr".to_string(),
        CType::Pointer { .. } => "ptr_ptr".to_string(),
    }
}

fn escape_kira_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            other => out.push(other),
        }
    }
    out
}
