//! Rendering a [`BindingModule`] as Kira source in the generated FFI dialect.
//!
//! The dialect is the one already in the language: `@FFI.Alias`, `@FFI.Array`,
//! `@FFI.Struct`, `@FFI.Callback`, and `@FFI.Pointer` ride a struct; `@FFI.Extern`
//! rides a bodyless function written with the `-> Type` result spelling. None
//! of it is generator-private — a binding is ordinary Kira source that a person
//! can read, edit into a hand-written seam, and compile with no generator in
//! the picture.
//!
//! Pure: a module in, a `String` out, no filesystem. What it emits is asserted
//! on directly rather than through a file.

use std::fmt::Write;

use super::model::{BindingModule, KiraType};

/// The line every generated binding opens with.
///
/// Load-bearing rather than decorative: it is what tells a reader — and the
/// cache adopting a file it did not write — that this file is generated.
pub const GENERATED_HEADER: &str = "// generated by kira FFI autobinding for";

/// Renders `module` as the Kira source of one binding file.
pub fn render(module: &BindingModule) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{GENERATED_HEADER} {}", module.library);
    let _ = writeln!(
        out,
        "// Edit the native-library declaration, not this generated file."
    );

    for opaque in &module.opaques {
        let _ = write!(
            out,
            "\n@FFI.Alias {{ target: {name} }}\nstruct {name} {{}}\n",
            name = opaque.name
        );
    }

    for array in &module.arrays {
        let _ = write!(
            out,
            "\n@FFI.Array {{ element: {element}, count: {count} }}\nstruct {name} {{}}\n",
            element = array.element.spelling(),
            count = array.count,
            name = array.name
        );
    }

    for callback in &module.callbacks {
        let params = callback
            .params
            .iter()
            .map(|param| param.spelling())
            .collect::<Vec<_>>()
            .join(", ");
        let _ = write!(
            out,
            "\n@FFI.Callback {{ abi: c, params: [{params}], result: {result} }}\n\
             struct {name} {{}}\n",
            result = callback.result.spelling(),
            name = callback.name
        );
    }

    for record in &module.structs {
        let _ = write!(
            out,
            "\n@FFI.Struct {{ layout: c }}\nstruct {} {{",
            record.name
        );
        if record.fields.is_empty() {
            let _ = writeln!(out, "}}");
            continue;
        }
        let _ = writeln!(out);
        for field in &record.fields {
            let _ = writeln!(
                out,
                "    var {}: {}",
                field.name,
                field.field_type.spelling()
            );
        }
        let _ = writeln!(out, "}}");
    }

    for pointer in &module.pointers {
        let _ = write!(
            out,
            "\n@FFI.Pointer {{ target: {target}, ownership: borrowed }}\nstruct {name} {{}}\n",
            target = pointer.target,
            name = pointer.name
        );
    }

    for function in &module.functions {
        let params = function
            .params
            .iter()
            .map(|param| format!("{}: {}", param.name, param.param_type.spelling()))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = write!(
            out,
            "\n@FFI.Extern {{ library: {library}, symbol: {symbol}, abi: c }}\n\
             function {symbol}({params}) -> {result}\n",
            library = module.library,
            symbol = function.symbol,
            result = function.result.spelling()
        );
    }

    for constant in &module.constants {
        let _ = write!(
            out,
            "\nlet {name}: Int = {value}\n",
            name = constant.name,
            value = constant.value
        );
    }

    if !module.skipped.is_empty() {
        let _ = write!(
            out,
            "\n// Declared by the headers and not bound, each for the reason given.\n\
             // Nothing below is a gap to be filled by hand: a hand-written \
             `@FFI.Extern`\n\
             // for one of these would be refused by the same rule that skipped it.\n"
        );
        for skipped in &module.skipped {
            let _ = writeln!(out, "// {}: {}", skipped.name, skipped.reason);
        }
    }

    out
}

/// The name a pointer alias to `target` is declared under.
pub fn pointer_alias_name(target: &str) -> String {
    format!("{target}_ptr")
}

/// The name an inline array typedef of `count` `element`s is declared under.
pub fn array_type_name(element: &KiraType, count: u64) -> String {
    format!("{}_array_{count}", element.spelling())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::autobind::model::{
        ArrayDecl, CallbackDecl, ConstantDecl, FieldDecl, FunctionDecl, OpaqueDecl, ParamDecl,
        PointerDecl, SkippedDecl, StructDecl,
    };

    fn sample() -> BindingModule {
        BindingModule {
            library: "kiratext".to_owned(),
            opaques: vec![OpaqueDecl {
                name: "kira_text_engine".to_owned(),
            }],
            arrays: vec![ArrayDecl {
                name: "I8_array_8".to_owned(),
                element: KiraType::Int("I8"),
                count: 8,
            }],
            structs: vec![StructDecl {
                name: "kira_text_vmetrics".to_owned(),
                fields: vec![
                    FieldDecl {
                        name: "ascender".to_owned(),
                        field_type: KiraType::F32,
                    },
                    FieldDecl {
                        name: "pad".to_owned(),
                        field_type: KiraType::Named("I8_array_8".to_owned()),
                    },
                ],
            }],
            callbacks: vec![CallbackDecl {
                name: "kira_text_hook".to_owned(),
                params: vec![KiraType::Int("I32"), KiraType::RawPtr],
                result: KiraType::Void,
            }],
            pointers: vec![PointerDecl {
                name: "kira_text_engine_ptr".to_owned(),
                target: "kira_text_engine".to_owned(),
            }],
            functions: vec![FunctionDecl {
                symbol: "kira_text_engine_create".to_owned(),
                params: vec![ParamDecl {
                    name: "seed".to_owned(),
                    param_type: KiraType::Int("I32"),
                }],
                result: KiraType::Named("kira_text_engine_ptr".to_owned()),
            }],
            constants: Vec::new(),
            skipped: vec![SkippedDecl {
                name: "kira_text_printf".to_owned(),
                reason: "a variadic C function has no fixed signature to bind".to_owned(),
            }],
        }
    }

    #[test]
    fn every_form_renders_in_the_dialect_the_language_already_reads() {
        let text = render(&sample());
        assert!(text.starts_with("// generated by kira FFI autobinding for kiratext\n"));
        assert!(
            text.contains("@FFI.Alias { target: kira_text_engine }\nstruct kira_text_engine {}")
        );
        assert!(text.contains("@FFI.Array { element: I8, count: 8 }\nstruct I8_array_8 {}"));
        assert!(text.contains(
            "@FFI.Callback { abi: c, params: [I32, RawPtr], result: Void }\n\
             struct kira_text_hook {}"
        ));
        assert!(text.contains(
            "@FFI.Struct { layout: c }\nstruct kira_text_vmetrics {\n\
             \x20   var ascender: F32\n    var pad: I8_array_8\n}"
        ));
        assert!(text.contains(
            "@FFI.Pointer { target: kira_text_engine, ownership: borrowed }\n\
             struct kira_text_engine_ptr {}"
        ));
        assert!(text.contains(
            "@FFI.Extern { library: kiratext, symbol: kira_text_engine_create, abi: c }\n\
             function kira_text_engine_create(seed: I32) -> kira_text_engine_ptr"
        ));
    }

    #[test]
    fn a_skipped_declaration_is_written_down_with_its_reason() {
        let text = render(&sample());
        assert!(
            text.contains("// kira_text_printf: a variadic C function has no fixed signature"),
            "{text}"
        );
    }

    #[test]
    fn a_constant_is_written_as_a_module_scope_let() {
        let module = BindingModule {
            library: "demo".to_owned(),
            constants: vec![
                ConstantDecl {
                    name: "DEMO_ONE".to_owned(),
                    value: 1,
                },
                ConstantDecl {
                    name: "DEMO_BACKWARDS".to_owned(),
                    value: -3,
                },
            ],
            ..BindingModule::default()
        };
        let text = render(&module);
        assert!(text.contains("\nlet DEMO_ONE: Int = 1\n"), "{text}");
        assert!(text.contains("\nlet DEMO_BACKWARDS: Int = -3\n"), "{text}");
    }

    #[test]
    fn a_field_less_struct_still_closes_its_body() {
        let module = BindingModule {
            library: "demo".to_owned(),
            structs: vec![StructDecl {
                name: "Empty".to_owned(),
                fields: Vec::new(),
            }],
            ..BindingModule::default()
        };
        assert!(render(&module).contains("struct Empty {}\n"));
    }

    #[test]
    fn generated_names_are_derived_the_one_way() {
        assert_eq!(pointer_alias_name("uint8_t"), "uint8_t_ptr");
        assert_eq!(array_type_name(&KiraType::Int("I8"), 56), "I8_array_56");
    }
}
