use std::collections::{HashMap, HashSet};

use crate::compiler::CompiledModule;
use crate::runtime::type_system::{KiraType, TypeId};

use super::error::AotError;

pub struct ExportedApi {
    pub structs: Vec<String>,
    pub functions: Vec<String>,
}

pub fn generate_c_header(
    project_name: &str,
    module: &CompiledModule,
    api: &ExportedApi,
) -> Result<String, AotError> {
    let mut out = String::new();
    out.push_str("// Generated by Kira — do not edit\n");
    out.push_str("#pragma once\n");
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <stdbool.h>\n\n");

    let exported_structs: HashSet<String> = api.structs.iter().cloned().collect();
    let mut struct_type_ids = Vec::new();
    for name in &api.structs {
        let type_id = module
            .types
            .resolve_named(name)
            .ok_or_else(|| AotError(format!("exported struct `{}` does not exist", name)))?;
        if !matches!(module.types.get(type_id), KiraType::Struct(_)) {
            return Err(AotError(format!(
                "`{}` is marked @Export but is not a struct",
                name
            )));
        }
        struct_type_ids.push(type_id);
    }

    let ordered_structs = topo_sort_structs(module, &struct_type_ids, &exported_structs)?;
    for type_id in ordered_structs {
        let KiraType::Struct(struct_type) = module.types.get(type_id) else {
            continue;
        };
        out.push_str("typedef struct { ");
        for (index, field) in struct_type.fields.iter().enumerate() {
            let c_ty = c_type_name(module, field.type_id, &exported_structs)?;
            if index > 0 {
                out.push(' ');
            }
            out.push_str(&format!("{} {};", c_ty, field.name));
        }
        out.push_str(&format!(" }} {};\n\n", struct_type.name));
    }

    for name in &api.functions {
        let function = module.functions.get(name).ok_or_else(|| {
            AotError(format!("exported function `{}` does not exist", name))
        })?;
        let ret = c_type_name(module, function.signature.return_type, &exported_structs)?;
        let mut params = Vec::new();
        for (index, type_id) in function.signature.params.iter().copied().enumerate() {
            let ty = c_type_name(module, type_id, &exported_structs)?;
            params.push(format!("{} arg{}", ty, index));
        }
        let params = if params.is_empty() {
            "void".to_string()
        } else {
            params.join(", ")
        };
        out.push_str(&format!("{} {}({});\n", ret, name, params));
    }

    if project_name.is_empty() {
        // appease lint; project_name is only used for nicer errors later.
    }

    Ok(out)
}

fn c_type_name(
    module: &CompiledModule,
    type_id: TypeId,
    exported_structs: &HashSet<String>,
) -> Result<String, AotError> {
    Ok(match module.types.get(type_id) {
        KiraType::Unit => "void".to_string(),
        KiraType::Int => "int64_t".to_string(),
        KiraType::Float => "double".to_string(),
        KiraType::Bool => "bool".to_string(),
        KiraType::String => "const char*".to_string(),
        KiraType::Struct(struct_type) => {
            if !exported_structs.contains(&struct_type.name) {
                return Err(AotError(format!(
                    "exported API references struct `{}` which is not marked @Export",
                    struct_type.name
                )));
            }
            struct_type.name.clone()
        }
        other => {
            return Err(AotError(format!(
                "C header generation does not support type {:?}",
                other
            )))
        }
    })
}

fn topo_sort_structs(
    module: &CompiledModule,
    struct_type_ids: &[TypeId],
    exported_structs: &HashSet<String>,
) -> Result<Vec<TypeId>, AotError> {
    let mut ordered = Vec::new();
    let mut perm = HashSet::new();
    let mut temp = HashSet::new();
    let mut id_to_name = HashMap::new();
    for type_id in struct_type_ids {
        let KiraType::Struct(st) = module.types.get(*type_id) else {
            continue;
        };
        id_to_name.insert(*type_id, st.name.clone());
    }

    fn visit(
        module: &CompiledModule,
        type_id: TypeId,
        exported_structs: &HashSet<String>,
        perm: &mut HashSet<TypeId>,
        temp: &mut HashSet<TypeId>,
        ordered: &mut Vec<TypeId>,
    ) -> Result<(), AotError> {
        if perm.contains(&type_id) {
            return Ok(());
        }
        if !temp.insert(type_id) {
            return Err(AotError("cycle detected in exported structs".to_string()));
        }

        let KiraType::Struct(struct_type) = module.types.get(type_id) else {
            return Ok(());
        };
        for field in &struct_type.fields {
            if let KiraType::Struct(child) = module.types.get(field.type_id) {
                if exported_structs.contains(&child.name) {
                    visit(module, field.type_id, exported_structs, perm, temp, ordered)?;
                }
            }
        }

        temp.remove(&type_id);
        perm.insert(type_id);
        ordered.push(type_id);
        Ok(())
    }

    for type_id in struct_type_ids.iter().copied() {
        visit(module, type_id, exported_structs, &mut perm, &mut temp, &mut ordered)?;
    }
    Ok(ordered)
}

