// KiraBridging.h — AUTO-GENERATED by kira build
// Do not edit.
#ifndef KIRA_BRIDGING_H
#define KIRA_BRIDGING_H

#define SOKOL_NO_ENTRY
#define SOKOL_METAL

#include "vendor/sokol/sokol_app.h"
#include "vendor/sokol/sokol_gfx.h"
#include "vendor/sokol/sokol_glue.h"
#include "vendor/sokol/sokol_log.h"

#endif
