[package]
name = "UIDemoSample"
version = "0.1.0"
kira = ">=1.0.0"
license = "Apache-2.0"

[targets]
macos = true
windows = true

[dependencies]
"Kira.Foundation" = "0.1.0"
"Kira.Graphics" = "0.1.0"

[build]
optimization = "debug"
hotReload = false
incrementalBuild = true
executionMode = "runtime"

[native.macos.signing]
teamID = "P8B46RAQ8D"
bundleID = "com.kira.uidemosample"
